from __future__ import annotations

import json
import os
import sys
import traceback
from pathlib import Path
from typing import Any


SCIENTIFIC_WARNING = (
    "Structural alignment is descriptive geometry only and does not imply conserved catalytic activity, "
    "binding affinity, stability, thermodynamic behavior, molecular dynamics behavior, or experimental validation."
)


def main() -> None:
    spec_path, result_path = _parse_args()
    spec = json.loads(Path(spec_path).read_text(encoding="utf-8"))

    try:
        if os.getenv("PYMOL_USE_PYMOL2") == "1":
            import pymol2

            with pymol2.PyMOL() as pymol_instance:
                payload = _run_alignment(pymol_instance.cmd, spec)
        else:
            from pymol import cmd

            payload = _run_alignment(cmd, spec)
            cmd.quit()
        _write_result(result_path, {"ok": True, **payload})
    except Exception as exc:
        _write_result(
            result_path,
            {
                "ok": False,
                "error": str(exc),
                "traceback": traceback.format_exc(),
            },
        )
        raise


def _run_alignment(cmd: Any, spec: dict[str, Any]) -> dict[str, Any]:
    cmd.reinitialize()
    cmd.load(spec["reference_path"], "reference")
    cmd.load(spec["mobile_path"], "mobile")
    cmd.remove("solvent")

    method = spec["method"]
    reference_selection = "reference and polymer"
    mobile_selection = "mobile and polymer"
    if method == "align":
        raw = cmd.align(mobile_selection, reference_selection)
    elif method == "super":
        raw = cmd.super(mobile_selection, reference_selection)
    elif method == "cealign":
        raw = cmd.cealign(reference_selection, mobile_selection)
    else:
        raise ValueError(f"Unsupported alignment method: {method}")

    rmsd, aligned_atoms = _parse_alignment_result(raw)
    artifacts: dict[str, str] = {}
    if spec.get("render"):
        image_path = Path(spec["image_path"])
        _render_alignment(cmd, spec, image_path)
        artifacts["image_path"] = str(image_path)

    pml_path = spec.get("pml_script_path")
    if pml_path:
        _write_pml(Path(pml_path), spec)
        artifacts["pml_script_path"] = str(pml_path)

    return {
        "result": {
            "rmsd_angstrom": rmsd,
            "aligned_atoms": aligned_atoms,
            "method": method,
            "reference_source": spec.get("reference_summary"),
            "mobile_source": spec.get("mobile_summary"),
        },
        "metadata": {
            "operation": "alignment",
            "method": method,
            "alignment_version": "0.2.0",
        },
        "warnings": [SCIENTIFIC_WARNING],
        "artifacts": artifacts,
    }


def _parse_alignment_result(raw: Any) -> tuple[float | None, int | None]:
    if isinstance(raw, dict):
        rmsd = raw.get("RMSD", raw.get("rmsd"))
        atoms = raw.get("alignment_length", raw.get("aligned_atoms"))
        return _float_or_none(rmsd), _int_or_none(atoms)
    if isinstance(raw, (list, tuple)):
        rmsd = raw[0] if len(raw) >= 1 else None
        atoms = raw[1] if len(raw) >= 2 else None
        return _float_or_none(rmsd), _int_or_none(atoms)
    return None, None


def _render_alignment(cmd: Any, spec: dict[str, Any], image_path: Path) -> None:
    image_path.parent.mkdir(parents=True, exist_ok=True)
    cmd.viewport(int(spec["width"]), int(spec["height"]))
    cmd.bg_color("white")
    cmd.set("orthoscopic", 1)
    cmd.set("ray_opaque_background", 1)
    cmd.set("antialias", 2)
    cmd.set("cartoon_fancy_helices", 1)
    cmd.hide("everything", "reference or mobile")
    cmd.show("cartoon", "reference and polymer")
    cmd.show("cartoon", "mobile and polymer")
    cmd.color("gray70", "reference and polymer")
    cmd.color("marine", "mobile and polymer")
    cmd.orient("reference or mobile")
    cmd.zoom("reference or mobile", buffer=6)
    cmd.png(
        str(image_path),
        width=int(spec["width"]),
        height=int(spec["height"]),
        dpi=int(spec["dpi"]),
        ray=1 if spec.get("ray", True) else 0,
        quiet=1,
    )


def _write_pml(path: Path, spec: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    method = spec["method"]
    lines = [
        "# Reproducible PyMOL alignment script generated by PyMOL Figure Agent.",
        "# Descriptive geometry only; not experimental validation.",
        f"load {Path(spec['reference_path']).as_posix()}, reference",
        f"load {Path(spec['mobile_path']).as_posix()}, mobile",
    ]
    if method == "cealign":
        lines.append("cealign reference and polymer, mobile and polymer")
    else:
        lines.append(f"{method} mobile and polymer, reference and polymer")
    lines.extend(
        [
            "hide everything, reference or mobile",
            "show cartoon, reference and polymer",
            "show cartoon, mobile and polymer",
            "color gray70, reference and polymer",
            "color marine, mobile and polymer",
            "zoom reference or mobile, 6",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _float_or_none(value: Any) -> float | None:
    try:
        return round(float(value), 3)
    except (TypeError, ValueError):
        return None


def _int_or_none(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _parse_args() -> tuple[str, str]:
    args = [arg for arg in sys.argv[1:] if arg != "--"]
    if len(args) < 2:
        raise SystemExit("Usage: alignment_job.py SPEC_JSON RESULT_JSON")
    return args[0], args[1]


def _write_result(result_path: str, result: dict[str, Any]) -> None:
    Path(result_path).write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
