from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from scene_operations import scene_operation_lines


def build_render_script_text(
    request: dict[str, Any],
    *,
    source_type: str,
    source_summary: dict[str, str],
    source_path: Path,
    image_path: Path,
    session_path: Path | None = None,
) -> str:
    width = int(request.get("width") or 1600)
    height = int(request.get("height") or 1200)
    dpi = int(request.get("dpi") or 300)
    ray = 1 if request.get("ray", True) else 0
    background = str(request.get("background") or "white")
    preset = str(request.get("preset") or "publication_cartoon")
    render_quality = str(request.get("render_quality") or "high")
    representations = list(request.get("representations") or [])
    color = str(request.get("color") or "chainbow")
    transparent = bool(request.get("transparent", False))
    show_ligands = bool(request.get("show_ligands", True))
    show_metals = bool(request.get("show_metals", True))
    show_solvent = bool(request.get("show_solvent", False))
    surface_transparency = float(request.get("surface_transparency") or 0.35)
    orient_selection = str(request.get("orient_selection") or "all")
    zoom_selection = str(request.get("zoom_selection") or orient_selection)

    lines = [
        "# Reproducible PyMOL render script generated by MolWeaver.",
        "# Local artifact intended for editing inside native PyMOL.",
        "reinitialize",
        _source_load_line(source_type, source_summary, source_path),
        f'viewport {width}, {height}',
        f'bg_color {background}',
        f"set ray_opaque_background, {0 if transparent else 1}",
        "set antialias, 2",
        "set orthoscopic, 1",
        "set depth_cue, 0",
        "set cartoon_fancy_helices, 1",
        "set cartoon_smooth_loops, 1",
        "set sphere_scale, 0.55",
        "set stick_radius, 0.18",
    ]

    if render_quality in {"high", "publication", "ultra"}:
        lines.extend(
            [
                "set surface_quality, 2",
                "set cartoon_sampling, 14",
                "set mesh_quality, 2",
                "set ray_trace_mode, 1",
                "set ray_trace_color, black",
                "set ray_trace_gain, 0.16",
                "set ray_trace_fog, 0",
                "set ray_trace_fog_start, 0",
                "set ray_shadow, 1",
            ]
        )
    else:
        lines.extend(
            [
                "set surface_quality, 1",
                "set cartoon_sampling, 10",
                "set mesh_quality, 2",
                "set ray_trace_mode, 0",
            ]
        )

    if not show_solvent:
        lines.append("remove (structure) and solvent")

    lines.append("hide everything, structure")
    lines.extend(_preset_lines(preset, surface_transparency))
    lines.extend(_representation_lines(representations))
    lines.extend(_color_lines(color))

    if show_ligands:
        lines.append("show sticks, (structure) and organic")
    if show_metals:
        lines.append("show spheres, (structure) and elem Cu+Zn+Fe+Mg+Mn+Ca+Na+K+Co+Ni")

    lines.extend(_highlight_lines(request.get("highlights") or []))
    lines.extend(_label_lines(request.get("labels") or []))
    operation_lines, operation_warnings = scene_operation_lines(
        request.get("operations") or [],
        object_name="structure",
    )
    lines.extend(operation_lines)
    for warning in operation_warnings:
        lines.append(f"# {warning}")
    lines.append(f"orient {orient_selection}")
    lines.append(f"zoom {zoom_selection}, 4")
    if session_path is not None:
        lines.append(f'save "{_quote_pymol_path(session_path)}"')
    lines.append(
        f'png "{_quote_pymol_path(image_path)}", width={width}, height={height}, dpi={dpi}, ray={ray}, quiet=1'
    )
    return "\n".join(lines) + "\n"


def _source_load_line(source_type: str, source_summary: dict[str, str], source_path: Path) -> str:
    if source_type == "pdb_id":
        pdb_id = source_summary.get("id") or source_path.stem
        return f"fetch {pdb_id}, structure, async=0"
    return f'load "{_quote_pymol_path(source_path)}", structure'


def _preset_lines(preset: str, surface_transparency: float) -> list[str]:
    lines: list[str] = []
    if preset == "minimal":
        lines.append("show cartoon, structure")
        return lines

    if preset in {"publication_cartoon", "ligand_focus", "active_site", "copper_sites"}:
        lines.extend(
            [
                "show cartoon, (structure) and polymer.protein",
                "show cartoon, (structure) and polymer.nucleic",
            ]
        )

    if preset in {"surface", "active_site"}:
        lines.extend(
            [
                "show surface, structure",
                f"set transparency, {surface_transparency:.3f}, structure",
            ]
        )

    if preset == "ligand_focus":
        lines.append("set cartoon_transparency, 0.25, structure")

    if preset == "copper_sites":
        lines.extend(
            [
                "show spheres, (structure) and elem Cu",
                'color orange, (structure) and elem Cu',
            ]
        )

    return lines


def _representation_lines(representations: list[Any]) -> list[str]:
    lines: list[str] = []
    for representation in representations:
        if representation in {"cartoon", "surface", "sticks", "spheres", "lines"}:
            lines.append(f"show {representation}, structure")
    return lines


def _color_lines(color: str) -> list[str]:
    text = color.strip()
    if text == "chainbow":
        return ["spectrum count, rainbow, structure"]
    if text == "spectrum":
        return ["spectrum count, rainbow, structure"]
    if text == "element":
        return ["color gray80, structure", "spectrum count, atomic, structure"]
    if text.startswith("#") and len(text) == 7:
        color_name, lines = _hex_color_lines(text, target="structure", return_name=True)
        lines.append(f"color {color_name}, structure")
        return lines
    return [f"color {text}, structure"]


def _highlight_lines(highlights: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for index, highlight in enumerate(highlights):
        selection = str(highlight.get("selection") or "all")
        representation = str(highlight.get("representation") or "sticks")
        color = str(highlight.get("color") or "yellow")
        lines.append(f"show {representation}, {selection}")
        if color.startswith("#") and len(color) == 7:
            color_name, color_lines = _hex_color_lines(color, target=selection, suffix=str(index), return_name=True)
            lines.extend(color_lines)
            lines.append(f"color {color_name}, {selection}")
        else:
            lines.append(f"color {color}, {selection}")
        if highlight.get("label"):
            lines.append(f"label {selection}, {repr(str(highlight['label']))}")
    return lines


def _label_lines(labels: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for item in labels:
        selection = str(item.get("selection") or "structure")
        text = str(item.get("text") or "resn + resi")
        if not _looks_like_pymol_label_expression(text):
            text = repr(text)
        lines.append(f"label {selection}, {text}")
    lines.extend(["set label_size, 22", "set label_color, black"])
    return lines


def _hex_color_lines(
    value: str,
    *,
    target: str,
    suffix: str = "",
    return_name: bool = False,
) -> list[str] | tuple[str, list[str]]:
    red = int(value[1:3], 16) / 255
    green = int(value[3:5], 16) / 255
    blue = int(value[5:7], 16) / 255
    name = f"api_color_{value[1:].lower()}{suffix}"
    lines = [f"set_color {name}, [{red:.3f}, {green:.3f}, {blue:.3f}]"]
    if return_name:
        return name, lines
    return lines


def _quote_pymol_path(path: Path) -> str:
    return path.as_posix().replace('"', '\\"')


def _looks_like_pymol_label_expression(value: str) -> bool:
    allowed = {"name", "resn", "resi", "chain", "segi", "elem", "oneletter"}
    tokens = {
        token.strip()
        for token in re.split(r"[\s+'\"]+", value.replace("+", " "))
        if token.strip()
    }
    return bool(tokens) and tokens.issubset(allowed)
